name: C/C++ CI

on:
  push:
    branches: [ "t-caf" ]
  pull_request:
    branches: [ "t-caf" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: apt update && apt upgrade -y && apt install -y gcc g++ cmake clang-12 clang-15 bc rsync cpio
    - name: configure-1
      run: apt install python2.7 && update-alternatives --install /usr/bin/python python /usr/bin/python2.7 500
    - name: configure-2
      run: apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig
    - name: configure-3
      run: apt-get install -y libx11-dev libreadline-dev libgl1-mesa-dev g++-multilib git flex bison gperf build-essential libncurses-dev tofrodos libxml2-utils xsltproc zlib1g-dev dpkg-dev libsdl1.2-dev gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev libgl1-mesa-dev libxml2-utils xsltproc unzip m4 lib32z1-dev ccache libssl-dev
    - name: configure-4
      run: wget https://www.openssl.org/source/openssl-3.0.7.tar.gz && tar -xf openssl-3.0.7.tar.gz && cd openssl-3.0.7 && ./config --prefix=/usr --openssldir=/usr shared zlib && make -j16 && make install
    - name: build
      run: bash compile.sh
